<?php
$_quote = $this->getMethod()->getInfoInstance()->getQuote();
?>
<div class="paynova-ssn-container">
    <input type="text" nam="payment[<?php echo $this->getMethod()->getCode() ?>][government_id]">
    <button name="getaddress-button" onclick="paynovaGetAddress(this);" type="button"><?php echo $this->__('Get Address') ?></button>
    <div class="address"></div>
</div>

<script>
    if (!('paynovaGetAddress' in window)) {
        function paynovaGetAddress(el) {
            var input = $(el).up('div').down('input');
            var governmentId = $(input).getValue();

            // Default to the quote country code for multi page checkouts,
            // otherwise use the selected billing country code
            var countryCode = <?php echo $this->helper('core')->jsonEncode($_quote->getBillingAddress()->getCountryCode()) ?>;
            var billingCountry = $('billing:country_id');
            if (billingCountry) {
                countryCode = $(billingCountry).getValue();
            }

            new Ajax.Request('<?php echo $this->getUrl('made_paynova/utility/getAddresses', array('_secure' => true)) ?>',
                {
                    method: 'post',
                    parameters: {
                        'country_code': countryCode,
                        'government_id': governmentId,
                        method: window.payment.currentMethod
                    },
                    onComplete: function (transport) {
                        var address = $(input).up('div').down('div');
                        $(address).update(transport.responseText);
                    }
                });
        };
    }
</script>