<div class="paynova-ssn-container">
    <input type="text" nam="payment[<?php echo $this->getMethod()->getCode() ?>]">
    <button name="getaddress-button" onclick="paynovaGetAddress(this);" type="button"><?php echo $this->__('Get Address') ?></button>
    <div class="address"></div>
</div>

<script>
    if (!('paynovaGetAddress' in window)) {
        function paynovaGetAddress(el) {
            var input = $(el).up('div').down('input');
            var ssn = $(input).getValue();

            new Ajax.Request('<?php echo $this->getUrl('made_paynova/utility/getAddress', array('_secure' => true)) ?>',
                {
                    method: 'post',
                    parameters: {
                        ssn: ssn,
                        method: window.payment.currentMethod
                    },
                    onComplete: function (transport) {
                        var address = $(input).up('div').down('div');
                        $(address).update(transport.responseText);
                    }
                });
        };
    }
</script>